### ISSUE TITLE
gnome+ibus，中文做为首选输入法时，启动gvim无法自动切换为英文。

### ISSUE THREAD

**Issue by yueduz** [kevinhwang91/vim-ibus-sw#10]

**Comment by kevinhwang91** [comment]
抱歉，现在才看到这个issue。这个插件是切换输入法，而不是内置选项的中英切换。基本应用场景是大于1个输入法。

**Comment by yueduz** [comment]
我确实是有两个输入法

kevinhwang91 <notifications@github.com> 于 2020年11月28日周六 00:53写道：

**Comment by kevinhwang91** [comment]
进入正常模式，会记录你的中文，并不会切换的。

一般使用情况是英文输入法进入正常模式，插入模式后用户手动切换中文，按esc回到正常模式就是英文输入法。

**Comment by kevinhwang91** [comment]
No reply
