### ISSUE TITLE
Very nice plugin, but currpted on dvorak keyboard layout.

### ISSUE THREAD

**Issue by Vssblt** [kevinhwang91/vim-ibus-sw#11]

**Comment by kevinhwang91** [comment]
This plugin never maps any keymaps. Give me more details, please.

**Comment by Vssblt** [comment]
System: Ubuntu 20.04
Software: neovim
IME: Ibus

I used the dvorak layout to input Chinese in insert mode, and when I exits from insert mode to normal mode, it switches to the English qwerty layout rather than English dvorak layout.

I have three input methods, English dvorak input method, English qwerty input method and Chinese input method.

The keyboard layout of Chinese input method does not have a fixed layout. Its layout is the same as the layout of the lasted keyboard used. Example, The Chinese input method will be qwerty when I switch input method from English qwerty to Chinese input method. The Chinese input layout will be dvorak When I switch input method from English dvorak to Chinese input method.

The plugin was not switched correctly. It just fixed switched to qwerty.

**Comment by kevinhwang91** [comment]
What key do you press when you exit from insert mode?  This plugin use `InsertLeave` event. `:h InsertLeave` for more details.
