### ISSUE TITLE
Custom key on gnome tweak 

### ISSUE THREAD

**Issue by cutbypham** [kevinhwang91/vim-ibus-sw#12]
- Problem is i need to set key again on gnome tweak when i use vim-ibus-sw plugin
- I use US default and VN <https://github.com/BambooEngine/ibus-bamboo/>
- My dotfiles: https://github.com/thuanpham2311/dotfiles
- I use Wayland (maybe this is a problem)
![image](https://user-images.githubusercontent.com/40050527/142713210-dba36522-b5dd-4dba-a4cc-bf67800e4055.png)
![image](https://user-images.githubusercontent.com/40050527/142713241-6aa940c6-d151-4a2c-b04d-0a942a585aa4.png)

**Comment by cutbypham** [comment]
**update: i switch to fedora 35, gnome 41.1 wayland**

- yep, keyboard setting at gnome tweak work fine 😃 
- but the plugin not working 😂

![image](https://user-images.githubusercontent.com/40050527/142854333-c8736299-ec29-4f02-bf43-8f67a2054433.png)

**Comment by kevinhwang91** [comment]
Yes, it must write a gnome-shell plugin to invoke `eval` method. dbus is disabled if gnome-shell version is greater than 41.
Please upgrade the plugin, I will fix it perfectly if I have plenty of time.

Your requirement from issue, I am afraid that it's hard to implement. Forgive me to close this issue.

**Comment by kevinhwang91** [comment]
FYI: https://github.com/kevinhwang91/vim-ibus-sw/issues/3
